### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by mustardamus** [tiaanduplessis/pomd#1]
```
/Users/mustardamus/.nvm/versions/node/v5.6.0/lib/node_modules/pomd/index.js:13
let timerRunning = false
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
$ node -v
v5.6.0
```

The straight forward solution is to add `'use strict'` after the shebang in your script.

**Comment by tiaanduplessis** [comment]
@mustardamus will add. Thanks for pointing out 👍
